django_tut/myproject/accounts/urls.py
from django.contrib.auth import views
from .views import ArticleListView
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
]

urlpatterns += [
    path('home/', ArticleListView.as_view(), name='home'),
]

django_tut/myproject/blog/urls.py
from django.urls import path
from .views import api, ArticleDetail, CategoryList, ArticleListView, AuthorList

app_name = 'blog'
urlpatterns = [
    path('api/', api, name='api'),
    path('home/', ArticleListView.as_view(), name='home'),
    path('home/<int:page>/', ArticleListView.as_view(), name='home'),
    path('article/<slug:slug>', ArticleDetail.as_view(), name='detail'),
    path('category/<slug:slug>', CategoryList.as_view(), name='category'),
    path('category/<slug:slug>/<int:page>/', CategoryList.as_view(), name='category'),
    path('author/<str:username>/<int:page>/', AuthorList.as_view(), name='author'),
    path('author/<str:username>', AuthorList.as_view(), name='author'),

]

django_tut/myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_tut/myproject/accounts/models.py
from django.db import models

# Create your models here.

django_tut/myproject/blog/models.py
from django.db import models
from django.utils import timezone
from extenstions.utils import jalali_convertor
from django.utils.html import format_html
from django.contrib.auth.models import User


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,
                               related_name='children', verbose_name='زیردسته بندی')
    title = models.CharField(max_length=100,verbose_name='عنوان')
    slug = models.SlugField(verbose_name='اسلاگ')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشین')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title
    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'draft'),
        ('p', 'published')
    )
    title = models.CharField(max_length=200,  verbose_name ='عنوان')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,
                               related_name='articles', verbose_name='نویسنده')
    slug = models.SlugField(max_length=100, unique=True,  verbose_name='اسلاگ')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی', related_name='articles')
    description = models.TextField(verbose_name='بدنه')
    thumbnail = models.ImageField(upload_to='images',  verbose_name ='تصویر')
    publish = models.DateTimeField(default=timezone.now(),  verbose_name ='انتشار')
    created = models.DateTimeField(auto_now_add=True,  verbose_name ='ساخته شده در ')
    updated = models.DateTimeField(auto_now=True,  verbose_name ='بروزرسانی شده در')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES,  verbose_name ='وضعیت')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_convertor(self.publish)
    jpublish.short_description = 'تاریخ انتشار'

    def category_published(self):
        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html('<img src={} width=100 height=75>'.format(self.thumbnail.url))
    thumbnail_tag.short_discription = 'تصویر'


    objects = ArticleManager()

django_tut/myproject/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from blog.models import Article

class ArticleListView(LoginRequiredMixin,ListView ):
    queryset = Article.objects.all()
    template_name = 'registration/home.html'
    context_object_name = 'articles'

django_tut/myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from .models import Article, Category
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User


def api(request):
    data = {
            "1": {
                'name': 'reza',
                'family': 'amin',
                'age': 23
            },
            "2": {
                'name': 'ali',
                'family': 'rezaei',
                'age': 23
            },

    }
    return JsonResponse(data)


# def home(request, page=1):
#     articles = Article.objects.published()
#     paginator = Paginator(articles, 2)
#     articles = paginator.get_page(page)
#     context = {
#         'articles': articles,
#         'category': Category.objects.filter(status=True)
#
#     }
#     return render(request, 'blog/home.html', context)

class ArticleListView(ListView):

    queryset = Article.objects.published()
    paginate_by = 2
    context_object_name = "articles"
    template_name = "blog/home.html"


# def detail(request, slug):
#     context = {
#         'article': get_object_or_404(Article, slug=slug)
#     }
#     return render(request, 'blog/article_detail.html', context)

class ArticleDetail(DetailView):
    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles_list = category.articles.published()
#     paginator = Paginator(articles_list, 2)
#     articles = paginator.get_page(page)
#     context = {
#         'category': category,
#         'articles': articles,
#     }
#     return render(request, 'blog/category.html', context)

class CategoryList(ListView):
    paginate_by = 2
    template_name = 'blog/category.html'
    context_object_name = 'articles'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 2
    template_name = 'blog/author_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

django_tut/myproject/blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

django_tut/myproject/blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block body %}
    <!-- Page Header-->
        <header class="masthead" style="background-image: url({{ article.thumbnail.url }})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>reza amin</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

            <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <h2 class="section-heading">{{ article.title }}</h2>
                        <p>{{ article.description }}</p>



                    </div>
                </div>
            </div>
        </article>

{% endblock %}

django_tut/myproject/blog/templates/blog/author_list.html
{% extends 'blog/base_list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">نویسنده:{{ author.get_full_name }}</h3>

{% endblock %}

{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}

{% endblock %}
{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

django_tut/myproject/blog/templates/blog/base.html
{% load static %}
{% load base_tag %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>

        <link rel="icon" type="image/x-icon" href={% static "blog/assets/favicon.ico" %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "blog/css/styles.css" %} rel="stylesheet" />
        <link href={% static "blog/css/rtl.css" %} rel="stylesheet" />
        {% block header %}{% endblock %}
    </head>
    <body>
        <!-- Navigation-->
{#        <a class="navbar-brand" href="home.html">{% title %}</a>#}

        {% category_navbar %}

        <!-- Main Content-->
        {% block body %}
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>

django_tut/myproject/blog/templates/blog/base_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}
    home
{% endblock %}

{% block body %}
    <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'blog/assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>reza amin</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
            <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">

                <div class="col-md-10 col-lg-8 col-xl-7">
                {% block header %}{% endblock %}
                    {% for article in articles %}
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' article.slug %}">
                            <h2 class="post-title">{{ article.title }}</h2>
                            <h3 class="post-subtitle">{{ article.description }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
                            {{ article.jpublish }}

                        </p>
                        <div>
                            {% for cat in article.category_published.published %}
                                <a href="{% url 'blog:category' cat.slug %}">{{ cat.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                {% endfor %}


                    <div class="d-flex justify-content-end mb-4">

                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary text-uppercase pager-button " href="{% block previous_page_url %}{% endblock %}">پست های قدیمی &lAarr;</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary text-uppercase pager-button " href="{% block next_page_url %}{% endblock %}">پست های جدید &rAarr;</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
{% endblock %}

django_tut/myproject/blog/templates/blog/category.html
{% extends 'blog/base_list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">دسته بندی:{{ category.title }}</h3>

{% endblock %}

{% block previous_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}

{% endblock %}
{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

django_tut/myproject/blog/templates/blog/home.html
{% extends 'blog/base_list.html' %}

{% block header %}

{% endblock %}


{% block previous_page_url %}
    {% url 'blog:home' page_obj.previous_page_number %}

{% endblock %}
{% block next_page_url %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

django_tut/myproject/blog/templates/blog/partials/category_loop.html
<ul class="navbar-nav ms-auto py-4 py-lg-0">
    {% for cat in cat.children.active %}
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{ cat.title }}</a>
            {% if cat.children.active %}
                {% include 'blog/partials/category_loop.html' %}

            {% endif %}
        </li>>
    {% endfor %}
</ul>>

django_tut/myproject/blog/templates/blog/partials/category_navbar.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">

            <div class="container px-4 px-lg-5">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">Home</a></li>
                        {% for cat in category %}
                            {% if cat.parent == None %}
                                <li class="nav-item">
                                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{ cat.title }}</a>
                                    {% if cat.children.active %}
                                        {% include 'blog/partials/category_loop.html' %}

                                    {% endif %}

                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </nav>

django_tut/myproject/blog/templates/blog/single.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block body %}
    <!-- Page Header-->
        <header class="masthead" style="background-image: url({{ article.thumbnail.url }})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>reza amin</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

            <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <h2 class="section-heading">{{ article.title }}</h2>
                        <p>{{ article.description }}</p>



                    </div>
                </div>
            </div>
        </article>

{% endblock %}